[package]
name = "wafer-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared interfaces, clients, and utilities for WAFER blocks"

[dependencies]
wafer-run = { path = "../wafer-run", default-features = false }
wafer-block = { path = "../wafer-block" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["serde", "std", "clock"] }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }

[lib]
name = "wafer_core"
path = "src/lib.rs"
