use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// CollectionDef defines a database collection (table).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollectionDef {
    /// Column name → column definition.
    pub fields: HashMap<String, FieldDef>,
    /// Secondary indexes declared on top of `fields` (excluding the primary key).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub indexes: Vec<IndexDef>,
}

/// FieldDef defines a field (column) in a collection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldDef {
    /// Logical column type (e.g. `"text"`, `"int"`, `"json"`); interpretation is backend-specific.
    #[serde(rename = "type")]
    pub field_type: String,
    /// `true` if this column participates in the primary key.
    #[serde(default)]
    pub primary: bool,
    /// `true` if values in this column must be unique across rows.
    #[serde(default)]
    pub unique: bool,
    /// `true` if NULL values are permitted (i.e. column is nullable).
    #[serde(default)]
    pub optional: bool,
    /// Optional default value applied when no value is provided on insert.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    /// `true` if values are auto-generated by the database (e.g. autoincrement).
    #[serde(default)]
    pub auto: bool,
    /// Foreign-key reference of the form `"collection.field"`; empty if no FK.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub r#ref: String,
}

/// IndexDef defines an index on a collection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndexDef {
    /// Ordered list of column names that make up the index key.
    pub fields: Vec<String>,
    /// `true` for a unique index, `false` for a plain (possibly multi-row) index.
    #[serde(default)]
    pub unique: bool,
}
