[package]
name = "middleware-chain"
version = "0.0.1"
edition = "2021"

[dependencies]
wafer-run  = { path = "../../crates/wafer-run", features = ["full"] }
wafer-block-inspector = { path = "../../crates/wafer-block-inspector" }
wafer-block-http-listener = { path = "../../crates/wafer-block-http-listener" }
wafer-block-security-headers = { path = "../../crates/wafer-block-security-headers" }
wafer-block-cors = { path = "../../crates/wafer-block-cors" }
wafer-block-router = { path = "../../crates/wafer-block-router" }

async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1"

[lints]
workspace = true
