//! `requires` given as a bare string (not an array) must be a spanned compile
//! error, not silently parsed into an empty ("unrestricted") list. The
//! runtime treats an empty `requires` as unrestricted (`context.rs:264`), so
//! swallowing malformed input here would silently disable the `call_block`
//! access-control gate.
//!
//! The struct implements `new()` and `Block` (like `pass_with_new.rs`) so
//! that, absent the `requires` bug, the macro would expand cleanly — the
//! compile failure this fixture asserts must come from `requires` parsing,
//! not from an unrelated missing-trait-impl error.

use wafer_block::{
    block::Block,
    context::Context,
    core_types::Message,
    streams::{input::InputStream, output::OutputStream},
    types::BlockInfo,
};
use wafer_block_macro::{wafer_async_trait, wafer_block};

struct Widget;

impl Widget {
    fn new() -> Self {
        Self
    }
}

#[wafer_async_trait]
impl Block for Widget {
    fn info(&self) -> BlockInfo {
        // Deliberately not `<Widget>::block_info()`: that associated function
        // is generated by `#[wafer_block]` below, and this fixture's whole
        // point is that the macro must fail to expand (bailing out before it
        // emits `block_info`). Referencing it here would produce a second,
        // unrelated "function not found" error on top of the one this test
        // asserts on.
        unreachable!()
    }
    async fn handle(
        &self,
        _ctx: &dyn Context,
        _msg: Message,
        _input: InputStream,
    ) -> OutputStream {
        OutputStream::drop_request()
    }
}

#[wafer_block(
    name = "acme/widget",
    version = "0.1.0",
    interface = "handler@v1",
    summary = "Test widget",
    requires = "wafer-run/database"
)]
impl Widget {
    fn handle(_msg: Message, _body: Vec<u8>) -> wafer_sdk::core_abi::GuestResult {
        wafer_sdk::core_abi::GuestResult::respond(vec![])
    }
}

fn main() {}
