/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Validate a WaferFlow JSON definition.
 *
 * Returns `null` on success, or a string describing validation errors.
 * CPU-only; stays sync.
 */
export declare function validateWaferflow(json: string): string | null
/**
 * The WAFER runtime, exposed as a JavaScript class.
 *
 * Usage from Node.js / TypeScript:
 * ```js
 * const { WaferRuntime } = require('wafer-run');
 * const w = new WaferRuntime();
 * await w.register('my-block', './block.wasm');
 * await w.register('main', './main-flow.json');
 * await w.resolve();
 * await w.start();
 * const result = JSON.parse(await w.run('main', JSON.stringify({ kind: 'test', data: '', meta: {} })));
 * await w.stop();
 * ```
 */
export declare class WaferRuntime {
  /** Create a new WAFER runtime instance. */
  constructor()
  /**
   * Register a block or flow definition from a file path.
   *
   * If `path` ends with `.wasm`, registers a WASM block with the given name.
   * Otherwise, reads the file as a JSON flow definition.
   */
  register(name: string, path: string): Promise<void>
  /** Resolve all block references in registered flows. */
  resolve(): Promise<void>
  /**
   * Start the runtime. Calls resolve() if not already resolved.
   *
   * Uses `start_without_bind()` because the Node.js dev server has its
   * own HTTP handling — blocks that spawn listeners are not needed here.
   */
  start(): Promise<void>
  /**
   * Stop the runtime and shut down all block instances.
   *
   * Must be awaited before the runtime is garbage-collected so that block
   * `lifecycle(Stop)` handlers can release resources (DB connections, file
   * handles, etc.). Drop will log a warning if this method was not called.
   */
  stop(): Promise<void>
  /**
   * Run a flow with the given message (body-less).
   *
   * Takes the flow ID and a JSON message string. Returns a JSON result string:
   * `{"action":"respond|drop|error|continue|halt","body":"...","meta":{...}}`
   *
   * Note: `halt` payloads use `body_base64` (Base64-encoded bytes) instead of
   * the `respond` action's `body` string — Halt may carry non-UTF-8 or empty bodies.
   */
  run(flowId: string, messageJson: string): Promise<string>
  /** Get info about all registered flows as a JSON array. */
  flowsInfo(): Promise<string>
  /** Check whether a block type is registered. */
  hasBlock(typeName: string): Promise<boolean>
}
