pub mod auth_validator;
pub mod config;
pub mod cors;
#[cfg(feature = "crypto")]
pub mod crypto;
#[cfg(feature = "http")]
pub mod http_listener;
#[cfg(feature = "http")]
pub mod http_server;
pub mod iam_guard;
pub mod inspector;
pub mod logger;
#[cfg(feature = "storage-local")]
pub mod local_storage;
pub mod monitoring;
#[cfg(feature = "network")]
pub mod network;
#[cfg(feature = "postgres")]
pub mod postgres;
pub mod ip_rate_limit;
pub mod readonly_guard;
pub mod router;
#[cfg(feature = "storage-s3")]
pub mod s3;
pub mod security_headers;
#[cfg(feature = "sqlite")]
pub mod sqlite;
pub mod web;

#[cfg(not(target_arch = "wasm32"))]
pub use config::ConfigBlock;
#[cfg(feature = "crypto")]
pub use crypto::CryptoBlock;
#[cfg(not(target_arch = "wasm32"))]
pub use logger::LoggerBlock;
#[cfg(feature = "network")]
pub use network::NetworkBlock;

