#!/usr/bin/env python3
"""Generate the TypeScript constant files for the wafer-client-js SDK.

Usage:
    python wafer-common/codegen/generate.py

Reads TOML definitions from wafer-common/definitions/ and emits TypeScript
files into wafer-common/generated/typescript/, mirrored into the
wafer-client-js SDK.

NOTE: the Rust and Go constants are NOT generated — they are hand-maintained
(Rust in the `wafer-block` crate's `common`/`meta`/`core_types` modules). This
generator drives the TypeScript SDK only.
"""

import os
import sys

# Ensure we can import from the codegen package
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

try:
    import tomllib
except ModuleNotFoundError:
    # Python < 3.11 fallback
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        print("ERROR: Python 3.11+ required (for tomllib), or install tomli: pip install tomli")
        sys.exit(1)

from templates import typescript


DEFINITIONS_DIR = os.path.join(ROOT_DIR, "definitions")
GENERATED_DIR = os.path.join(ROOT_DIR, "generated")


def read_toml(filename: str) -> dict:
    path = os.path.join(DEFINITIONS_DIR, filename)
    with open(path, "rb") as f:
        return tomllib.load(f)


def write_file(subdir: str, filename: str, content: str) -> None:
    out_dir = os.path.join(GENERATED_DIR, subdir)
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, filename)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, ROOT_DIR)}")


def main() -> None:
    print("wafer-common codegen: reading definitions...")

    # Load definitions
    error_codes_data = read_toml("error_codes.toml")
    meta_keys_data = read_toml("meta_keys.toml")
    service_names_data = read_toml("service_names.toml")

    codes = error_codes_data["codes"]

    # Flatten meta keys into section.key -> value for templates
    meta_flat = {}
    for section, entries in meta_keys_data.items():
        if isinstance(entries, dict):
            # Handle nested sections like request.prefixes
            for sub_key, sub_val in entries.items():
                if isinstance(sub_val, dict):
                    meta_flat[f"{section}.{sub_key}"] = sub_val
                else:
                    meta_flat.setdefault(section, {})[sub_key] = sub_val
        else:
            meta_flat[section] = entries

    # --- TypeScript ---
    print("generating TypeScript...")
    write_file("typescript", "error-codes.ts", typescript.generate_error_codes(codes))
    write_file("typescript", "meta-keys.ts", typescript.generate_meta_keys(meta_flat))
    write_file("typescript", "service-names.ts", typescript.generate_service_names(service_names_data))

    # TypeScript barrel export
    ts_constants = "\n".join([
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "export { ErrorCode, type ErrorCodeType } from './error-codes.js';",
        "export * from './meta-keys.js';",
        "export { ServiceName, ServiceOp } from './service-names.js';",
        "",
    ])
    write_file("typescript", "constants.ts", ts_constants)

    # Mirror the TypeScript outputs into the wafer-client-js SDK so it can
    # `import` them directly (its tsconfig forbids imports outside src/).
    print("mirroring TypeScript into wafer-client-js...")
    sdk_dir = os.path.join(ROOT_DIR, "..", "packages", "wafer-client-js", "src", "generated")
    os.makedirs(sdk_dir, exist_ok=True)
    for filename, content in [
        ("error-codes.ts", typescript.generate_error_codes(codes)),
        ("meta-keys.ts", typescript.generate_meta_keys(meta_flat)),
        ("service-names.ts", typescript.generate_service_names(service_names_data)),
        ("constants.ts", ts_constants),
    ]:
        path = os.path.join(sdk_dir, filename)
        with open(path, "w") as f:
            f.write(content)
        print(f"  wrote {os.path.relpath(path, ROOT_DIR)}")

    print("done.")


if __name__ == "__main__":
    main()
