#!/usr/bin/env python3
"""Generate language-specific constant files from WAFER TOML definitions.

Usage:
    python wafer-common/codegen/generate.py

Reads TOML definitions from wafer-common/definitions/ and emits Rust, Go,
and TypeScript files into wafer-common/generated/.
"""

import os
import sys

# Ensure we can import from the codegen package
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

try:
    import tomllib
except ModuleNotFoundError:
    # Python < 3.11 fallback
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        print("ERROR: Python 3.11+ required (for tomllib), or install tomli: pip install tomli")
        sys.exit(1)

from templates import rust, go, typescript


DEFINITIONS_DIR = os.path.join(ROOT_DIR, "definitions")
GENERATED_DIR = os.path.join(ROOT_DIR, "generated")


def read_toml(filename: str) -> dict:
    path = os.path.join(DEFINITIONS_DIR, filename)
    with open(path, "rb") as f:
        return tomllib.load(f)


def write_file(subdir: str, filename: str, content: str) -> None:
    out_dir = os.path.join(GENERATED_DIR, subdir)
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, filename)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, ROOT_DIR)}")


def main() -> None:
    print("wafer-common codegen: reading definitions...")

    # Load definitions
    error_codes_data = read_toml("error_codes.toml")
    meta_keys_data = read_toml("meta_keys.toml")
    service_names_data = read_toml("service_names.toml")

    codes = error_codes_data["codes"]

    # Flatten meta keys into section.key -> value for templates
    meta_flat = {}
    for section, entries in meta_keys_data.items():
        if isinstance(entries, dict):
            # Handle nested sections like request.prefixes
            for sub_key, sub_val in entries.items():
                if isinstance(sub_val, dict):
                    meta_flat[f"{section}.{sub_key}"] = sub_val
                else:
                    meta_flat.setdefault(section, {})[sub_key] = sub_val
        else:
            meta_flat[section] = entries

    # --- Rust ---
    print("generating Rust...")
    write_file("rust", "error_codes.rs", rust.generate_error_codes(codes))
    write_file("rust", "meta_keys.rs", rust.generate_meta_keys(meta_flat))
    write_file("rust", "service_names.rs", rust.generate_service_names(service_names_data))
    write_file("rust", "constants.rs", rust.generate_constants(True, True, True))

    # --- Go ---
    print("generating Go...")
    write_file("go", "error_codes.go", go.generate_error_codes(codes))
    write_file("go", "meta_keys.go", go.generate_meta_keys(meta_flat))
    write_file("go", "service_names.go", go.generate_service_names(service_names_data))

    # --- TypeScript ---
    print("generating TypeScript...")
    write_file("typescript", "error-codes.ts", typescript.generate_error_codes(codes))
    write_file("typescript", "meta-keys.ts", typescript.generate_meta_keys(meta_flat))
    write_file("typescript", "service-names.ts", typescript.generate_service_names(service_names_data))

    # TypeScript barrel export
    ts_constants = "\n".join([
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "export { ErrorCode, type ErrorCodeType } from './error-codes.js';",
        "export { MetaKey } from './meta-keys.js';",
        "export { ServiceName, ServiceOp } from './service-names.js';",
        "",
    ])
    write_file("typescript", "constants.ts", ts_constants)

    print("done.")


if __name__ == "__main__":
    main()
