//! Native Rust definitions for core WAFER types.
//!
//! These types were previously generated by `wit-bindgen` from the WIT interface
//! definitions. They are now hand-written to remove the wasmtime/WIT dependency
//! as part of the migration to wasmi + JSON ABI.

use std::fmt;

use serde::{Deserialize, Serialize};

/// A key-value metadata entry.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MetaEntry {
    pub key: String,
    pub value: String,
}

/// A message flowing through the block flow.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Message {
    pub kind: String,
    pub data: Vec<u8>,
    pub meta: Vec<MetaEntry>,
}

/// The action a block wants the runtime to take after processing a message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Action {
    Continue,
    Respond,
    Drop,
    Error,
}

/// A response payload returned when a block short-circuits the flow.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Response {
    pub data: Vec<u8>,
    pub meta: Vec<MetaEntry>,
}

/// gRPC-style error codes for WAFER.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    Ok,
    Cancelled,
    Unknown,
    InvalidArgument,
    DeadlineExceeded,
    NotFound,
    AlreadyExists,
    PermissionDenied,
    ResourceExhausted,
    FailedPrecondition,
    Aborted,
    OutOfRange,
    Unimplemented,
    Internal,
    Unavailable,
    DataLoss,
    Unauthenticated,
}

impl fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(self, f)
    }
}

/// A structured error returned by a block.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WaferError {
    pub code: ErrorCode,
    pub message: String,
    pub meta: Vec<MetaEntry>,
}

impl fmt::Display for WaferError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}: {}", self.code, self.message)
    }
}

/// The result of processing a message.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BlockResult {
    pub action: Action,
    pub response: Option<Response>,
    pub error: Option<WaferError>,
    pub message: Option<Message>,
}

/// How many block instances are created and when.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InstanceMode {
    PerNode,
    Singleton,
    PerFlow,
    PerExecution,
}

/// The kind of lifecycle event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LifecycleType {
    Init,
    Start,
    Stop,
}

/// A lifecycle event sent to blocks during transitions.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LifecycleEvent {
    pub event_type: LifecycleType,
    pub data: Vec<u8>,
}

/// Alias for BlockResult — common in block handler return types.
pub type Result_ = BlockResult;
