//! Native Rust definitions for core WAFER types.
//!
//! These types were previously generated by `wit-bindgen` from the WIT interface
//! definitions. They are now hand-written to remove the wasmtime/WIT dependency
//! as part of the migration to wasmi + JSON ABI.

use std::fmt;

use serde::{Deserialize, Serialize};

/// A key-value metadata entry.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MetaEntry {
    pub key: String,
    pub value: String,
}

/// A message flowing through the block flow.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Message {
    pub kind: String,
    pub meta: Vec<MetaEntry>,
}

/// gRPC-style error codes for WAFER.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    Ok,
    Cancelled,
    Unknown,
    InvalidArgument,
    DeadlineExceeded,
    NotFound,
    AlreadyExists,
    PermissionDenied,
    ResourceExhausted,
    FailedPrecondition,
    Aborted,
    OutOfRange,
    Unimplemented,
    Internal,
    Unavailable,
    DataLoss,
    Unauthenticated,
}

impl fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(self, f)
    }
}

/// A structured error returned by a block.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WaferError {
    pub code: ErrorCode,
    pub message: String,
    pub meta: Vec<MetaEntry>,
}

impl fmt::Display for WaferError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}: {}", self.code, self.message)
    }
}

/// How many block instances are created and when.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InstanceMode {
    PerNode,
    Singleton,
    PerFlow,
    PerExecution,
}

/// The kind of lifecycle event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LifecycleType {
    Init,
    Start,
    Stop,
}

/// A lifecycle event sent to blocks during transitions.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LifecycleEvent {
    pub event_type: LifecycleType,
    pub data: Vec<u8>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_code_serialization() {
        let json = serde_json::to_string(&ErrorCode::Internal).unwrap();
        assert_eq!(json, "\"Internal\"");

        let code: ErrorCode = serde_json::from_str("\"InvalidArgument\"").unwrap();
        assert_eq!(code, ErrorCode::InvalidArgument);
    }

    #[test]
    fn test_instance_mode_serialization() {
        let json = serde_json::to_string(&InstanceMode::PerNode).unwrap();
        assert_eq!(json, "\"PerNode\"");

        let mode: InstanceMode = serde_json::from_str("\"Singleton\"").unwrap();
        assert_eq!(mode, InstanceMode::Singleton);
    }

    #[test]
    fn message_has_no_data_field() {
        let m = Message {
            kind: "POST".to_string(),
            meta: vec![MetaEntry {
                key: "k".into(),
                value: "v".into(),
            }],
        };
        assert_eq!(m.kind, "POST");
        assert_eq!(m.meta.len(), 1);
    }
}
