//! Native Rust definitions for core WAFER types.
//!
//! These types were previously generated by `wit-bindgen` from the WIT interface
//! definitions. They are now hand-written to remove the wasmtime/WIT dependency
//! as part of the migration to wasmi + JSON ABI.

use std::fmt;

use serde::{Deserialize, Serialize};

/// A key-value metadata entry.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MetaEntry {
    /// Dotted key name (e.g. `req.action`, `auth.user_id`). See [`crate::meta`]
    /// for the well-known constants.
    pub key: String,
    /// String-encoded value associated with `key`.
    pub value: String,
}

/// A message flowing through the block flow.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Message {
    /// Message kind/action discriminator (e.g. HTTP method, service op name).
    pub kind: String,
    /// Out-of-band attributes attached to the message.
    pub meta: Vec<MetaEntry>,
}

/// gRPC-style error codes for WAFER.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    /// Operation completed successfully (rarely used in errors).
    Ok,
    /// Operation was cancelled by the caller.
    Cancelled,
    /// Unknown error; the source did not classify it.
    Unknown,
    /// Caller supplied an invalid argument.
    InvalidArgument,
    /// Deadline expired before the operation could complete.
    DeadlineExceeded,
    /// Requested resource does not exist.
    NotFound,
    /// Resource being created already exists.
    AlreadyExists,
    /// Caller lacks permission for the operation.
    PermissionDenied,
    /// A quota or rate limit was exhausted.
    ResourceExhausted,
    /// Operation rejected because the system is not in the required state.
    FailedPrecondition,
    /// Operation was aborted (often due to a concurrency conflict).
    Aborted,
    /// Operation attempted past the valid range.
    OutOfRange,
    /// Operation is not implemented or not supported.
    Unimplemented,
    /// Internal invariant violated.
    Internal,
    /// Service is temporarily unavailable.
    Unavailable,
    /// Unrecoverable data loss or corruption.
    DataLoss,
    /// Caller did not provide valid authentication credentials.
    Unauthenticated,
}

impl fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(self, f)
    }
}

/// A structured error returned by a block.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WaferError {
    /// Coarse error classification, modeled on gRPC status codes.
    pub code: ErrorCode,
    /// Human-readable error message.
    pub message: String,
    /// Structured key/value attributes (e.g. resource name, retry hint).
    pub meta: Vec<MetaEntry>,
}

impl fmt::Display for WaferError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}: {}", self.code, self.message)
    }
}

/// How many block instances are created and when.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InstanceMode {
    /// One instance per node (the runtime process).
    PerNode,
    /// One instance shared across the entire deployment.
    Singleton,
    /// One instance per flow definition.
    PerFlow,
    /// A fresh instance for every execution.
    PerExecution,
}

/// The kind of lifecycle event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LifecycleType {
    /// First-time initialization (run migrations, seed defaults).
    Init,
    /// Block is being brought online and may begin serving requests.
    Start,
    /// Block is being shut down; release resources.
    Stop,
}

/// A lifecycle event sent to blocks during transitions.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LifecycleEvent {
    /// Which lifecycle transition triggered this event.
    pub event_type: LifecycleType,
    /// Opaque event payload (codec-encoded by the sender).
    pub data: Vec<u8>,
}

/// A named binary blob carried alongside a `call_block` invocation.
///
/// Attached by the caller via `Context::call_block_with_attachments` (or, on
/// wasmi guests, the SDK's `RequestStream::attach`); read by the callee via
/// `Context::lookup_attachment`. Lifetime is per-`call_block` invocation —
/// attachments do not propagate beyond the immediate callee.
///
/// Encoded via `wafer_block::codec` (rmp-serde), so multi-MiB byte payloads
/// cross the host↔guest boundary without JSON-array inflation.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Attachment {
    /// MIME type of the payload (e.g. `image/png`, `application/pdf`).
    pub mime: String,
    /// Raw payload bytes (not base64 — encoded directly by MessagePack).
    pub bytes: Vec<u8>,
    /// Optional client-supplied filename.
    pub filename: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_code_serialization() {
        let json = serde_json::to_string(&ErrorCode::Internal).unwrap();
        assert_eq!(json, "\"Internal\"");

        let code: ErrorCode = serde_json::from_str("\"InvalidArgument\"").unwrap();
        assert_eq!(code, ErrorCode::InvalidArgument);
    }

    #[test]
    fn test_instance_mode_serialization() {
        let json = serde_json::to_string(&InstanceMode::PerNode).unwrap();
        assert_eq!(json, "\"PerNode\"");

        let mode: InstanceMode = serde_json::from_str("\"Singleton\"").unwrap();
        assert_eq!(mode, InstanceMode::Singleton);
    }

    #[test]
    fn message_has_no_data_field() {
        let m = Message {
            kind: "POST".to_string(),
            meta: vec![MetaEntry {
                key: "k".into(),
                value: "v".into(),
            }],
        };
        assert_eq!(m.kind, "POST");
        assert_eq!(m.meta.len(), 1);
    }

    #[test]
    fn attachment_codec_roundtrip_no_inflation() {
        use crate::codec;
        let original = Attachment {
            mime: "image/png".into(),
            bytes: vec![0u8; 1024 * 1024],
            filename: Some("cat.png".into()),
        };
        let encoded = codec::encode(&original).expect("encode");
        // 1 MiB body + small framing for {mime, filename}. Allow 5% headroom —
        // the load-bearing invariant: rmp does not array-encode Vec<u8>.
        assert!(
            encoded.len() < 1024 * 1024 + (1024 * 1024 / 20),
            "encoded size {} exceeds 1.05 MiB — Attachment::bytes inflation regressed",
            encoded.len()
        );
        let decoded: Attachment = codec::decode(&encoded).expect("decode");
        assert_eq!(decoded.mime, "image/png");
        assert_eq!(decoded.bytes.len(), 1024 * 1024);
        assert_eq!(decoded.filename.as_deref(), Some("cat.png"));
    }
}
