use crate::meta::*;
use crate::types::hashmap_to_meta;
use crate::{Action, Message, MetaEntry, Response, Result_, WaferError};
use std::collections::HashMap;

/// Extension trait for the `Message` type generated by wit-bindgen.
/// This allows it to emulate the ergonomic methods from the old `types.rs`.
pub trait MessageExt {
    fn var(&self, name: &str) -> &str;
    fn query(&self, name: &str) -> &str;
    fn header(&self, name: &str) -> &str;
    fn respond(&self, r: Response) -> Result_;
    fn drop_msg(&self) -> Result_;
    fn cont(&self) -> Result_;
    fn err(&self, e: WaferError) -> Result_;
}

impl MessageExt for Message {
    fn var(&self, name: &str) -> &str {
        let key = format!("{}{}", META_REQ_PARAM_PREFIX, name);
        self.get_meta(&key)
    }

    fn query(&self, name: &str) -> &str {
        let key = format!("{}{}", META_REQ_QUERY_PREFIX, name);
        self.get_meta(&key)
    }

    fn header(&self, name: &str) -> &str {
        let key = format!("http.header.{}", name);
        let val = self.get_meta(&key);
        if !val.is_empty() {
            return val;
        }
        let key_lower = format!("http.header.{}", name.to_lowercase());
        self.get_meta(&key_lower)
    }

    fn respond(&self, r: Response) -> Result_ {
        Result_ {
            action: Action::Respond,
            response: Some(r),
            error: None,
            message: Some(self.clone()),
        }
    }

    fn drop_msg(&self) -> Result_ {
        Result_ {
            action: Action::Drop,
            response: None,
            error: None,
            message: Some(self.clone()),
        }
    }

    fn cont(&self) -> Result_ {
        Result_ {
            action: Action::Continue,
            response: None,
            error: None,
            message: Some(self.clone()),
        }
    }

    fn err(&self, e: WaferError) -> Result_ {
        Result_ {
            action: Action::Error,
            response: None,
            error: Some(e),
            message: Some(self.clone()),
        }
    }
}

/// Respond returns a Result with a response body and content type.
pub fn respond(msg: &Message, data: Vec<u8>, content_type: &str) -> Result_ {
    let mut meta = Vec::new();
    if !content_type.is_empty() {
        meta.push(MetaEntry {
            key: META_RESP_CONTENT_TYPE.to_string(),
            value: content_type.to_string(),
        });
    }
    msg.respond(Response { data, meta })
}

/// Error returns an error Result with an error code and message.
pub fn error(msg: &Message, err_code: impl Into<crate::ErrorCode>, err_message: &str) -> Result_ {
    let err_code = err_code.into();
    Result_ {
        action: Action::Error,
        error: Some(WaferError {
            code: err_code,
            message: err_message.to_string(),
            meta: Vec::new(),
        }),
        response: None,
        message: Some(msg.clone()),
    }
}

/// JSONRespond marshals data as JSON and returns a response.
pub fn json_respond<T: serde::Serialize>(msg: &Message, data: &T) -> Result_ {
    match serde_json::to_vec(data) {
        Ok(body) => respond(msg, body, "application/json"),
        Err(e) => error(msg, crate::ErrorCode::Internal, &e.to_string()),
    }
}

/// ErrBadRequest returns an invalid argument error.
pub fn err_bad_request(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::InvalidArgument, message)
}

/// ErrUnauthorized returns an unauthenticated error.
pub fn err_unauthorized(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::Unauthenticated, message)
}

/// ErrForbidden returns a permission denied error.
pub fn err_forbidden(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::PermissionDenied, message)
}

/// ErrNotFound returns a not found error.
pub fn err_not_found(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::NotFound, message)
}

/// ErrConflict returns an already exists error.
pub fn err_conflict(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::AlreadyExists, message)
}

/// ErrValidation returns a validation error.
pub fn err_validation(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::InvalidArgument, message)
}

/// ErrInternal returns an internal error.
pub fn err_internal(msg: &Message, message: &str) -> Result_ {
    error(msg, crate::ErrorCode::Internal, message)
}

/// ResponseBuilder builds responses with headers and cookies.
pub struct ResponseBuilder {
    msg: Message,
    meta: HashMap<String, String>,
    cookie_count: usize,
}

impl ResponseBuilder {
    /// Create a new response builder.
    pub fn new(msg: &Message) -> Self {
        Self {
            msg: msg.clone(),
            meta: HashMap::new(),
            cookie_count: 0,
        }
    }

    /// Set an explicit status code override (e.g. 201, 301, 302).
    pub fn status(mut self, status: u16) -> Self {
        self.meta
            .insert(META_RESP_STATUS.to_string(), status.to_string());
        self
    }

    /// SetCookie adds a Set-Cookie header to the response.
    pub fn set_cookie(mut self, cookie: &str) -> Self {
        self.meta.insert(
            format!("{}{}", META_RESP_COOKIE_PREFIX, self.cookie_count),
            cookie.to_string(),
        );
        self.cookie_count += 1;
        self
    }

    /// SetHeader adds a response header.
    pub fn set_header(mut self, key: &str, value: &str) -> Self {
        self.meta.insert(
            format!("{}{}", META_RESP_HEADER_PREFIX, key),
            value.to_string(),
        );
        self
    }

    /// JSON marshals data as JSON and returns a response.
    pub fn json<T: serde::Serialize>(mut self, data: &T) -> Result_ {
        match serde_json::to_vec(data) {
            Ok(body) => {
                self.meta.insert(
                    META_RESP_CONTENT_TYPE.to_string(),
                    "application/json".to_string(),
                );
                self.msg.respond(Response {
                    data: body,
                    meta: hashmap_to_meta(self.meta),
                })
            }
            Err(e) => error(&self.msg, crate::ErrorCode::Internal, &e.to_string()),
        }
    }

    /// Body sets the response body with the given content type.
    pub fn body(mut self, data: Vec<u8>, content_type: &str) -> Result_ {
        if !content_type.is_empty() {
            self.meta.insert(
                META_RESP_CONTENT_TYPE.to_string(),
                content_type.to_string(),
            );
        }
        self.msg.respond(Response {
            data,
            meta: hashmap_to_meta(self.meta),
        })
    }
}

/// Respond with serialised JSON (no HTTP meta). Used by internal service blocks.
pub fn respond_json<T: serde::Serialize>(msg: &Message, data: &T) -> Result_ {
    match serde_json::to_vec(data) {
        Ok(body) => msg.respond(Response {
            data: body,
            meta: Vec::new(),
        }),
        Err(e) => msg.err(WaferError {
            code: crate::ErrorCode::Internal,
            message: e.to_string(),
            meta: Vec::new(),
        }),
    }
}

/// Respond with an empty body (no data, no meta). Used by service blocks for void operations.
pub fn respond_empty(msg: &Message) -> Result_ {
    Result_ {
        action: Action::Respond,
        response: Some(Response {
            data: Vec::new(),
            meta: Vec::new(),
        }),
        error: None,
        message: Some(msg.clone()),
    }
}

/// Convenience function to create a new ResponseBuilder.
pub fn new_response(msg: &Message) -> ResponseBuilder {
    ResponseBuilder::new(msg)
}
