//! Runtime-specific types and convenience impls on WIT-generated types.
//!
//! The WIT types (`Message`, `Action`, `BlockResult`, `ErrorCode`, etc.) are
//! generated by `wit_bindgen::generate!()` in `lib.rs`. This module adds:
//!
//! - Runtime-only types not in WIT (`BlockInfo`, `AdminUIInfo`, `BlockRuntime`, `RequestAction`)
//! - Ergonomic constructors and helpers on WIT types
//! - Backward-compatible `SCREAMING_CASE` constants on `ErrorCode`

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Runtime-only types (not part of WIT)
// ---------------------------------------------------------------------------

/// Metadata for a block's admin UI panel.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AdminUIInfo {
    pub label: String,
    pub description: String,
    /// URL path to the block's management UI (e.g. "/blocks/admin/frontend/").
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub url: String,
}

/// Whether a block runs natively or as WASM.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum BlockRuntime {
    Native,
    Wasm,
}

/// Runtime block info — extends the WIT `block-info` with runtime-specific fields.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BlockInfo {
    pub name: String,
    pub version: String,
    pub interface: String,
    pub summary: String,
    pub instance_mode: crate::InstanceMode,
    pub allowed_modes: Vec<crate::InstanceMode>,
    pub admin_ui: Option<AdminUIInfo>,
    pub runtime: BlockRuntime,
    pub requires: Vec<String>,
    /// Database collections this block requires. The runtime ensures these
    /// tables exist when the block is registered.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub collections: Vec<CollectionSchema>,
    /// JSON Schema describing the configuration this block accepts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config_schema: Option<serde_json::Value>,
}

// ---------------------------------------------------------------------------
// Interface specs
// ---------------------------------------------------------------------------

/// Specification for a block interface — the contract that blocks with
/// this interface must fulfil.
///
/// Describes what the interface does, what actions it handles, and the
/// expected message/response shapes per action.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct InterfaceSpec {
    /// Interface identifier, e.g. `"middleware@v1"`.
    pub name: String,
    /// Human-readable description of what blocks with this interface do.
    pub description: String,
    /// Per-action specifications. Key is the action name (e.g. `"retrieve"`,
    /// `"query"`). An empty map means the interface is action-agnostic
    /// (e.g. middleware that passes any message through).
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub actions: HashMap<String, ActionSpec>,
}

/// Specification for a single action within an interface.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ActionSpec {
    /// What this action does.
    pub description: String,
    /// JSON Schema describing the expected message `data` for this action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message_schema: Option<serde_json::Value>,
    /// JSON Schema describing the response `data` for this action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_schema: Option<serde_json::Value>,
}

/// A database collection (table) declared by a block.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CollectionSchema {
    pub name: String,
    pub fields: Vec<FieldSchema>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub indexes: Vec<IndexSchema>,
}

/// A field (column) in a collection.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FieldSchema {
    pub name: String,
    pub field_type: String,
    #[serde(default)]
    pub unique: bool,
    #[serde(default)]
    pub optional: bool,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub default_value: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub reference: String,
}

/// An index on a collection.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct IndexSchema {
    pub fields: Vec<String>,
    #[serde(default)]
    pub unique: bool,
}

// ---------------------------------------------------------------------------
// Schema builder helpers
// ---------------------------------------------------------------------------

impl CollectionSchema {
    pub fn new(name: &str) -> Self {
        Self { name: name.to_string(), fields: Vec::new(), indexes: Vec::new() }
    }

    pub fn field(mut self, name: &str, field_type: &str) -> Self {
        self.fields.push(FieldSchema::new(name, field_type));
        self
    }

    pub fn field_unique(mut self, name: &str, field_type: &str) -> Self {
        self.fields.push(FieldSchema::new(name, field_type).set_unique());
        self
    }

    pub fn field_optional(mut self, name: &str, field_type: &str) -> Self {
        self.fields.push(FieldSchema::new(name, field_type).set_optional());
        self
    }

    pub fn field_default(mut self, name: &str, field_type: &str, default: &str) -> Self {
        self.fields.push(FieldSchema::new(name, field_type).set_default(default));
        self
    }

    pub fn field_ref(mut self, name: &str, field_type: &str, reference: &str) -> Self {
        self.fields.push(FieldSchema::new(name, field_type).set_ref(reference));
        self
    }

    pub fn index(mut self, fields: &[&str]) -> Self {
        self.indexes.push(IndexSchema { fields: fields.iter().map(|s| s.to_string()).collect(), unique: false });
        self
    }

    pub fn unique_index(mut self, fields: &[&str]) -> Self {
        self.indexes.push(IndexSchema { fields: fields.iter().map(|s| s.to_string()).collect(), unique: true });
        self
    }
}

impl FieldSchema {
    pub fn new(name: &str, field_type: &str) -> Self {
        Self {
            name: name.to_string(),
            field_type: field_type.to_string(),
            unique: false,
            optional: false,
            default_value: String::new(),
            reference: String::new(),
        }
    }

    pub fn set_unique(mut self) -> Self { self.unique = true; self }
    pub fn set_optional(mut self) -> Self { self.optional = true; self }
    pub fn set_default(mut self, val: &str) -> Self { self.default_value = val.to_string(); self }
    pub fn set_ref(mut self, reference: &str) -> Self { self.reference = reference.to_string(); self }
}

/// A UI route declared by a block for SSR page serving.
///
/// Blocks declare their page routes via `Block::ui_routes()`. The router
/// automatically prefixes each path with `/b/{block_short_name}`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UiRoute {
    /// Relative path (e.g., "/login", "/dashboard", "/").
    pub path: String,
    /// Required roles to access this route.
    /// Empty = public, `["*"]` = any authenticated user, `["admin"]` = admin only.
    pub roles: Vec<String>,
}

impl UiRoute {
    pub fn new(path: &str, roles: &[&str]) -> Self {
        Self {
            path: path.to_string(),
            roles: roles.iter().map(|r| r.to_string()).collect(),
        }
    }

    /// Public route — no authentication required.
    pub fn public(path: &str) -> Self {
        Self::new(path, &[])
    }

    /// Authenticated route — any logged-in user.
    pub fn authenticated(path: &str) -> Self {
        Self::new(path, &["*"])
    }

    /// Admin-only route.
    pub fn admin(path: &str) -> Self {
        Self::new(path, &["admin"])
    }
}

/// HTTP-level request action mapped from method to WAFER semantics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RequestAction {
    Retrieve,
    Create,
    Update,
    Delete,
    Execute,
}

impl RequestAction {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Retrieve => "retrieve",
            Self::Create => "create",
            Self::Update => "update",
            Self::Delete => "delete",
            Self::Execute => "execute",
        }
    }
}

// ---------------------------------------------------------------------------
// ErrorCode backward-compatible constants
// ---------------------------------------------------------------------------

impl crate::ErrorCode {
    pub const OK: Self = Self::Ok;
    pub const CANCELLED: Self = Self::Cancelled;
    pub const UNKNOWN: Self = Self::Unknown;
    pub const INVALID_ARGUMENT: Self = Self::InvalidArgument;
    pub const DEADLINE_EXCEEDED: Self = Self::DeadlineExceeded;
    pub const NOT_FOUND: Self = Self::NotFound;
    pub const ALREADY_EXISTS: Self = Self::AlreadyExists;
    pub const PERMISSION_DENIED: Self = Self::PermissionDenied;
    pub const RESOURCE_EXHAUSTED: Self = Self::ResourceExhausted;
    pub const FAILED_PRECONDITION: Self = Self::FailedPrecondition;
    pub const ABORTED: Self = Self::Aborted;
    pub const OUT_OF_RANGE: Self = Self::OutOfRange;
    pub const UNIMPLEMENTED: Self = Self::Unimplemented;
    pub const INTERNAL: Self = Self::Internal;
    pub const UNAVAILABLE: Self = Self::Unavailable;
    pub const DATA_LOSS: Self = Self::DataLoss;
    pub const UNAUTHENTICATED: Self = Self::Unauthenticated;
}

impl From<&str> for crate::ErrorCode {
    fn from(s: &str) -> Self {
        match s {
            "ok" => Self::Ok,
            "cancelled" => Self::Cancelled,
            "unknown" => Self::Unknown,
            "invalid_argument" | "invalid-argument" | "bad_request" => Self::InvalidArgument,
            "deadline_exceeded" | "deadline-exceeded" => Self::DeadlineExceeded,
            "not_found" | "not-found" => Self::NotFound,
            "already_exists" | "already-exists" => Self::AlreadyExists,
            "permission_denied" | "permission-denied" => Self::PermissionDenied,
            "resource_exhausted" | "resource-exhausted" => Self::ResourceExhausted,
            "failed_precondition" | "failed-precondition" => Self::FailedPrecondition,
            "aborted" => Self::Aborted,
            "out_of_range" | "out-of-range" => Self::OutOfRange,
            "unimplemented" | "not_implemented" => Self::Unimplemented,
            "internal" => Self::Internal,
            "unavailable" => Self::Unavailable,
            "data_loss" | "data-loss" => Self::DataLoss,
            "unauthenticated" => Self::Unauthenticated,
            _ => Self::Unknown,
        }
    }
}

// ---------------------------------------------------------------------------
// WaferError helpers
// ---------------------------------------------------------------------------

impl crate::WaferError {
    /// Create a new error with the given code and message (empty meta).
    pub fn new(code: impl Into<crate::ErrorCode>, message: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            meta: Vec::new(),
        }
    }
}

// ---------------------------------------------------------------------------
// Message helpers
// ---------------------------------------------------------------------------

impl crate::Message {
    /// Create a new message with the given kind and data (empty meta).
    pub fn new(kind: impl Into<String>, data: impl AsRef<[u8]>) -> Self {
        Self {
            kind: kind.into(),
            data: data.as_ref().to_vec(),
            meta: Vec::new(),
        }
    }

    /// Get a meta value by key, returning `""` if not found.
    pub fn get_meta(&self, key: &str) -> &str {
        self.meta
            .iter()
            .find(|entry| entry.key == key)
            .map(|entry| entry.value.as_str())
            .unwrap_or("")
    }

    /// Set a meta value, updating an existing entry or appending a new one.
    pub fn set_meta(&mut self, key: impl Into<String>, value: impl Into<String>) {
        let key = key.into();
        let value = value.into();
        if let Some(entry) = self.meta.iter_mut().find(|e| e.key == key) {
            entry.value = value;
        } else {
            self.meta.push(crate::MetaEntry { key, value });
        }
    }

    /// Return a Drop result (like `drop_msg` but takes `&self` instead of consuming).
    pub fn drop_msg_ref(&self) -> crate::BlockResult {
        crate::BlockResult {
            action: crate::Action::Drop,
            response: None,
            error: None,
            message: Some(self.clone()),
        }
    }

    /// Return a Continue result carrying a clone of this message.
    pub fn cont_ref(&self) -> crate::BlockResult {
        crate::BlockResult {
            action: crate::Action::Continue,
            response: None,
            error: None,
            message: Some(self.clone()),
        }
    }

    /// Deserialize `data` as JSON into `T`.
    pub fn decode<T: serde::de::DeserializeOwned>(&self) -> Result<T, String> {
        serde_json::from_slice(&self.data).map_err(|e| e.to_string())
    }

    /// Shortcut for `get_meta(META_REQ_ACTION)`.
    pub fn action(&self) -> &str {
        self.get_meta(crate::meta::META_REQ_ACTION)
    }

    /// Shortcut for `get_meta(META_REQ_RESOURCE)`.
    pub fn path(&self) -> &str {
        self.get_meta(crate::meta::META_REQ_RESOURCE)
    }

    /// Shortcut for the authenticated user ID.
    pub fn user_id(&self) -> &str {
        self.get_meta(crate::meta::META_AUTH_USER_ID)
    }

    /// Shortcut for `get_meta("req.client.ip")`.
    pub fn remote_addr(&self) -> &str {
        self.get_meta(crate::meta::META_REQ_CLIENT_IP)
    }

    /// Get a cookie value by name from the Cookie header.
    pub fn cookie(&self, name: &str) -> &str {
        let cookies = self.header("cookie");
        if cookies.is_empty() {
            return "";
        }
        for part in cookies.split(';') {
            let part = part.trim();
            if let Some(eq) = part.find('=') {
                if &part[..eq] == name {
                    return &part[eq + 1..];
                }
            }
        }
        ""
    }

    /// Get an HTTP header value (case-insensitive).
    pub fn header(&self, name: &str) -> &str {
        let key = format!("http.header.{}", name);
        let val = self.get_meta(&key);
        if !val.is_empty() {
            return val;
        }
        let key_lower = format!("http.header.{}", name.to_lowercase());
        self.get_meta(&key_lower)
    }

    /// Get a URL path variable by name (from `req.param.{name}`).
    pub fn var(&self, name: &str) -> &str {
        let key = format!("{}{}", crate::meta::META_REQ_PARAM_PREFIX, name);
        self.get_meta(&key)
    }

    /// Get a query parameter by name (from `req.query.{name}`).
    pub fn query(&self, name: &str) -> &str {
        let key = format!("{}{}", crate::meta::META_REQ_QUERY_PREFIX, name);
        self.get_meta(&key)
    }

    /// Get the raw body bytes.
    pub fn body(&self) -> &[u8] {
        &self.data
    }

    /// Set data from a serializable value.
    pub fn set_data<T: serde::Serialize>(&mut self, data: &T) -> Result<(), String> {
        self.data = serde_json::to_vec(data).map_err(|e| e.to_string())?;
        Ok(())
    }

    /// Collect all query parameters into a HashMap.
    pub fn query_params(&self) -> HashMap<String, String> {
        let prefix = crate::meta::META_REQ_QUERY_PREFIX;
        self.meta
            .iter()
            .filter(|e| e.key.starts_with(prefix))
            .map(|e| (e.key[prefix.len()..].to_string(), e.value.clone()))
            .collect()
    }

    /// Parse pagination query parameters (page, page_size, offset).
    pub fn pagination_params(&self, default_page_size: usize) -> (usize, usize, usize) {
        let page: usize = self.query("page").parse().unwrap_or(1).max(1);
        let page_size: usize = self
            .query("page_size")
            .parse()
            .unwrap_or(default_page_size)
            .min(100);
        let offset = (page - 1) * page_size;
        (page, page_size, offset)
    }
}

// ---------------------------------------------------------------------------
// BlockResult helpers
// ---------------------------------------------------------------------------

impl crate::BlockResult {
    /// Create an error result with no message.
    pub fn error(err: crate::WaferError) -> Self {
        Self {
            action: crate::Action::Error,
            response: None,
            error: Some(err),
            message: None,
        }
    }
}

// ---------------------------------------------------------------------------
// MetaAccess trait for Vec<MetaEntry>
// ---------------------------------------------------------------------------

/// Convenience trait giving `HashMap`-like access to `Vec<MetaEntry>`.
pub trait MetaAccess {
    fn get(&self, key: &str) -> Option<&str>;
    fn set(&mut self, key: String, value: String);
    fn contains_key(&self, key: &str) -> bool;
}

impl MetaAccess for Vec<crate::MetaEntry> {
    fn get(&self, key: &str) -> Option<&str> {
        self.iter()
            .find(|e| e.key == key)
            .map(|e| e.value.as_str())
    }

    fn set(&mut self, key: String, value: String) {
        if let Some(entry) = self.iter_mut().find(|e| e.key == key) {
            entry.value = value;
        } else {
            self.push(crate::MetaEntry { key, value });
        }
    }

    fn contains_key(&self, key: &str) -> bool {
        self.iter().any(|e| e.key == key)
    }
}

impl MetaAccess for [crate::MetaEntry] {
    fn get(&self, key: &str) -> Option<&str> {
        self.iter()
            .find(|e| e.key == key)
            .map(|e| e.value.as_str())
    }

    fn set(&mut self, _key: String, _value: String) {
        panic!("cannot insert into a slice; use Vec<MetaEntry> instead");
    }

    fn contains_key(&self, key: &str) -> bool {
        self.iter().any(|e| e.key == key)
    }
}

/// Convert a `HashMap<String, String>` into `Vec<MetaEntry>`.
pub fn hashmap_to_meta(map: HashMap<String, String>) -> Vec<crate::MetaEntry> {
    map.into_iter()
        .map(|(k, v)| crate::MetaEntry { key: k, value: v })
        .collect()
}

/// Convert `Vec<MetaEntry>` into `HashMap<String, String>`.
pub fn meta_to_hashmap(meta: &[crate::MetaEntry]) -> HashMap<String, String> {
    meta.iter()
        .map(|e| (e.key.clone(), e.value.clone()))
        .collect()
}

// ---------------------------------------------------------------------------
// InstanceMode helpers
// ---------------------------------------------------------------------------

impl std::fmt::Display for crate::InstanceMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            crate::InstanceMode::PerNode => write!(f, "per-node"),
            crate::InstanceMode::Singleton => write!(f, "singleton"),
            crate::InstanceMode::PerFlow => write!(f, "per-flow"),
            crate::InstanceMode::PerExecution => write!(f, "per-execution"),
        }
    }
}

impl crate::InstanceMode {
    /// Parse an instance mode from a string (e.g. from flow config).
    pub fn parse(s: &str) -> Self {
        match s {
            "singleton" => Self::Singleton,
            "per-flow" => Self::PerFlow,
            "per-execution" => Self::PerExecution,
            _ => Self::PerNode,
        }
    }
}

// ---------------------------------------------------------------------------
// BlockRuntime helpers
// ---------------------------------------------------------------------------

impl Default for BlockRuntime {
    fn default() -> Self {
        Self::Native
    }
}

// ---------------------------------------------------------------------------
// BlockResult helpers (continued)
// ---------------------------------------------------------------------------

impl crate::BlockResult {
    /// Create a continue result carrying the given message.
    pub fn continue_with(msg: crate::Message) -> Self {
        Self {
            action: crate::Action::Continue,
            response: None,
            error: None,
            message: Some(msg),
        }
    }
}
