//! Runtime-specific types and convenience impls on WIT-generated types.
//!
//! The WIT types (`Message`, `Action`, `BlockResult`, `ErrorCode`, etc.) are
//! generated by `wit_bindgen::generate!()` in `lib.rs`. This module adds:
//!
//! - Runtime-only types not in WIT (`BlockInfo`, `AdminUIInfo`, `BlockRuntime`, `RequestAction`)
//! - Ergonomic constructors and helpers on WIT types
//! - Backward-compatible `SCREAMING_CASE` constants on `ErrorCode`

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Runtime-only types (not part of WIT)
// ---------------------------------------------------------------------------

/// HTTP method for block endpoints.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum HttpMethod {
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "PATCH")]
    Patch,
    #[serde(rename = "DELETE")]
    Delete,
}

impl std::fmt::Display for HttpMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Get => f.write_str("GET"),
            Self::Post => f.write_str("POST"),
            Self::Patch => f.write_str("PATCH"),
            Self::Delete => f.write_str("DELETE"),
        }
    }
}

/// Access level required for a block endpoint.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AuthLevel {
    #[default]
    Public,
    Authenticated,
    Admin,
}

impl std::fmt::Display for AuthLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Public => f.write_str("public"),
            Self::Authenticated => f.write_str("authenticated"),
            Self::Admin => f.write_str("admin"),
        }
    }
}

/// Block category — determines how the block is displayed in the admin UI.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum BlockCategory {
    /// User/admin-facing feature blocks (Auth, Products, Files, etc.)
    Feature,
    /// Internal service blocks (Database, Storage, Config, etc.)
    Service,
    /// System infrastructure and middleware (HTTP Listener, Router, CORS, etc.)
    Infrastructure,
    /// Uncategorized / third-party blocks.
    #[default]
    Misc,
}

/// Whether a block runs as native code or as a sandboxed WASM component.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum BlockRuntime {
    #[default]
    Native,
    Wasm,
}

// ---------------------------------------------------------------------------
// WRAP — Resource access grants
// ---------------------------------------------------------------------------

/// Resource type for typed grants. `None` matches any type.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ResourceType {
    /// Database collections (get, list, create, update, delete)
    Db,
    /// Configuration keys (get, set)
    Config,
    /// Storage folders and files (get, put, delete, list)
    Storage,
    /// Per-block crypto key namespaces (sign, verify)
    Crypto,
    /// Outbound network access (HTTP requests)
    Network,
}

impl std::fmt::Display for ResourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Db => f.write_str("db"),
            Self::Config => f.write_str("config"),
            Self::Storage => f.write_str("storage"),
            Self::Crypto => f.write_str("crypto"),
            Self::Network => f.write_str("network"),
        }
    }
}

impl ResourceType {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "db" => Some(Self::Db),
            "config" => Some(Self::Config),
            "storage" => Some(Self::Storage),
            "crypto" => Some(Self::Crypto),
            "network" => Some(Self::Network),
            _ => None,
        }
    }
}

/// A resource access grant declared by a block.
///
/// Blocks can only grant access to resources they own (enforced at startup).
/// The runtime collects all grants and checks them in `call_block()`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ResourceGrant {
    /// Block ID that receives this grant, or `"*"` for all blocks.
    pub grantee: String,
    /// Exact resource name or prefix pattern ending with `*`.
    pub resource: String,
    /// If true, the grantee can both read and write. If false, read-only.
    #[serde(default)]
    pub write: bool,
    /// Resource type this grant applies to. `None` = all types (wildcard).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<ResourceType>,
}

impl ResourceGrant {
    /// Create a read-only grant (all resource types).
    pub fn read(grantee: &str, resource: &str) -> Self {
        Self {
            grantee: grantee.to_string(),
            resource: resource.to_string(),
            write: false,
            resource_type: None,
        }
    }

    /// Create a read-write grant (all resource types).
    pub fn read_write(grantee: &str, resource: &str) -> Self {
        Self {
            grantee: grantee.to_string(),
            resource: resource.to_string(),
            write: true,
            resource_type: None,
        }
    }

    /// Restrict this grant to a specific resource type.
    pub fn typed(mut self, rt: ResourceType) -> Self {
        self.resource_type = Some(rt);
        self
    }
}

fn default_true() -> bool {
    true
}
fn default_instance_mode() -> crate::InstanceMode {
    crate::InstanceMode::PerNode
}

/// Block metadata — identity, schema declarations, and admin UI metadata.
///
/// Only `name`, `version`, `interface`, and `summary` are required.
/// All other fields have sensible defaults via `Default`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BlockInfo {
    // -- Core identity --
    pub name: String,
    pub version: String,
    pub interface: String,
    pub summary: String,
    #[serde(default = "default_instance_mode")]
    pub instance_mode: crate::InstanceMode,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub requires: Vec<String>,

    // -- Schema declarations --
    /// Database collections this block requires. The runtime ensures these
    /// tables exist when the block is registered.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub collections: Vec<CollectionSchema>,
    /// Configuration variables declared by this block.
    /// Each block should only declare variables with its own `{ORG}__{BLOCK}__` prefix.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub config_keys: Vec<ConfigVar>,
    /// WRAP resource access grants declared by this block.
    /// Blocks can only grant access to resources they own (enforced at startup).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub grants: Vec<ResourceGrant>,

    // -- Admin / UI metadata --
    /// Block category for admin UI grouping.
    #[serde(default)]
    pub category: BlockCategory,
    /// Whether this block runs as native code or WASM.
    #[serde(default)]
    pub runtime: BlockRuntime,
    /// Whether this block can be disabled by the admin.
    #[serde(default)]
    pub can_disable: bool,
    /// Whether the block is enabled by default on first run.
    #[serde(default = "default_true")]
    pub default_enabled: bool,
    /// Longer description of what the block does and how to use it.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
    /// HTTP endpoints exposed by this block.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub endpoints: Vec<BlockEndpoint>,
    /// URL path to the block's admin UI (e.g., `/b/products/admin/`).
    /// Empty if the block has no admin UI.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub admin_url: String,
}

impl Default for BlockInfo {
    fn default() -> Self {
        Self::new("", "", "", "")
    }
}

impl BlockInfo {
    /// Create a new BlockInfo with the four required fields.
    /// All other fields use sensible defaults.
    pub fn new(
        name: impl Into<String>,
        version: impl Into<String>,
        interface: impl Into<String>,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            version: version.into(),
            interface: interface.into(),
            summary: summary.into(),
            instance_mode: crate::InstanceMode::PerNode,
            requires: Vec::new(),
            collections: Vec::new(),
            config_keys: Vec::new(),
            grants: Vec::new(),
            category: BlockCategory::default(),
            runtime: BlockRuntime::default(),
            can_disable: false,
            default_enabled: true,
            description: String::new(),
            endpoints: Vec::new(),
            admin_url: String::new(),
        }
    }

    pub fn instance_mode(mut self, mode: crate::InstanceMode) -> Self {
        self.instance_mode = mode;
        self
    }

    pub fn requires(mut self, requires: Vec<String>) -> Self {
        self.requires = requires;
        self
    }

    pub fn collections(mut self, collections: Vec<CollectionSchema>) -> Self {
        self.collections = collections;
        self
    }

    pub fn config_keys(mut self, config_keys: Vec<BlockConfigKey>) -> Self {
        self.config_keys = config_keys;
        self
    }

    pub fn grants(mut self, grants: Vec<ResourceGrant>) -> Self {
        self.grants = grants;
        self
    }

    pub fn category(mut self, category: BlockCategory) -> Self {
        self.category = category;
        self
    }

    pub fn runtime(mut self, runtime: BlockRuntime) -> Self {
        self.runtime = runtime;
        self
    }

    pub fn can_disable(mut self, can_disable: bool) -> Self {
        self.can_disable = can_disable;
        self
    }

    pub fn default_enabled(mut self, default_enabled: bool) -> Self {
        self.default_enabled = default_enabled;
        self
    }

    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = description.into();
        self
    }

    pub fn endpoints(mut self, endpoints: Vec<BlockEndpoint>) -> Self {
        self.endpoints = endpoints;
        self
    }

    pub fn admin_url(mut self, url: impl Into<String>) -> Self {
        self.admin_url = url.into();
        self
    }
}

/// An HTTP endpoint exposed by a block.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BlockEndpoint {
    pub method: HttpMethod,
    pub path: String,
    pub summary: String,
    #[serde(default)]
    pub auth: AuthLevel,
}

impl BlockEndpoint {
    pub fn get(path: &str, summary: &str, auth: AuthLevel) -> Self {
        Self {
            method: HttpMethod::Get,
            path: path.into(),
            summary: summary.into(),
            auth,
        }
    }
    pub fn post(path: &str, summary: &str, auth: AuthLevel) -> Self {
        Self {
            method: HttpMethod::Post,
            path: path.into(),
            summary: summary.into(),
            auth,
        }
    }
    pub fn patch(path: &str, summary: &str, auth: AuthLevel) -> Self {
        Self {
            method: HttpMethod::Patch,
            path: path.into(),
            summary: summary.into(),
            auth,
        }
    }
    pub fn delete(path: &str, summary: &str, auth: AuthLevel) -> Self {
        Self {
            method: HttpMethod::Delete,
            path: path.into(),
            summary: summary.into(),
            auth,
        }
    }
}

/// Input type for config variable UI rendering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum InputType {
    #[default]
    Text,
    Toggle,
    Password,
    Color,
    Url,
}

/// A configuration variable declared by a block.
///
/// This is the single source of truth for config variable metadata.
/// Validation rules are derived from naming conventions:
/// - Sensitive (masked in API): `input_type == Password`
/// - Can't be emptied: `input_type == Password`
/// - Can't be deleted: key starts with `SOLOBASE_SHARED__`
/// - URL validated on write: `input_type == Url`
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ConfigVar {
    /// Full config key (e.g., `SUPPERS_AI__AUTH__JWT_SECRET`).
    pub key: String,
    /// Display label for the admin UI (e.g., "JWT Secret").
    #[serde(default)]
    pub name: String,
    /// What this variable controls.
    #[serde(default)]
    pub description: String,
    /// Default value if not set.
    #[serde(default)]
    pub default: String,
    /// Input type for UI rendering and validation.
    #[serde(default)]
    pub input_type: InputType,
    /// Optional warning shown in the admin UI (e.g., "Changing this invalidates sessions").
    #[serde(default)]
    pub warning: String,
    /// If true, a random value is auto-generated when the variable doesn't exist.
    /// Used for secrets like JWT signing keys and webhook HMAC secrets.
    #[serde(default)]
    pub auto_generate: bool,
}

impl ConfigVar {
    /// Create a config var with key, description, and default value.
    /// Use builder methods for additional metadata (name, input_type, warning).
    pub fn new(key: &str, description: &str, default: &str) -> Self {
        Self {
            key: key.into(),
            name: String::new(),
            description: description.into(),
            default: default.into(),
            input_type: InputType::Text,
            warning: String::new(),
            auto_generate: false,
        }
    }

    pub fn name(mut self, name: &str) -> Self {
        self.name = name.into();
        self
    }

    pub fn description(mut self, description: &str) -> Self {
        self.description = description.into();
        self
    }

    pub fn default_value(mut self, default: &str) -> Self {
        self.default = default.into();
        self
    }

    pub fn input_type(mut self, input_type: InputType) -> Self {
        self.input_type = input_type;
        self
    }

    pub fn warning(mut self, warning: &str) -> Self {
        self.warning = warning.into();
        self
    }

    /// Mark this variable as auto-generated if not provided.
    /// On first startup, a random secret is generated and stored.
    pub fn auto_generate(mut self) -> Self {
        self.auto_generate = true;
        self
    }

    /// Whether this variable is sensitive (should be masked in API responses).
    pub fn is_sensitive(&self) -> bool {
        self.input_type == InputType::Password
    }

    /// Whether this variable needs URL validation on write.
    pub fn is_url(&self) -> bool {
        self.input_type == InputType::Url
    }

    /// Whether this variable can be deleted by an admin.
    /// Shared system vars cannot be deleted.
    pub fn is_deletable(&self) -> bool {
        !self.key.starts_with("SOLOBASE_SHARED__")
    }

    /// Whether this variable can be set to an empty value.
    /// Sensitive vars (passwords/secrets) cannot be emptied.
    pub fn can_be_empty(&self) -> bool {
        !self.is_sensitive()
    }
}

/// Backward-compatible alias for `ConfigVar`.
pub type BlockConfigKey = ConfigVar;

// ---------------------------------------------------------------------------
// Interface specs
// ---------------------------------------------------------------------------

/// Specification for a block interface — the contract that blocks with
/// this interface must fulfil.
///
/// Describes what the interface does, what actions it handles, and the
/// expected message/response shapes per action.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct InterfaceSpec {
    /// Interface identifier, e.g. `"middleware@v1"`.
    pub name: String,
    /// Human-readable description of what blocks with this interface do.
    pub description: String,
    /// Per-action specifications. Key is the action name (e.g. `"retrieve"`,
    /// `"query"`). An empty map means the interface is action-agnostic
    /// (e.g. middleware that passes any message through).
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub actions: HashMap<String, ActionSpec>,
}

/// Specification for a single action within an interface.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ActionSpec {
    /// What this action does.
    pub description: String,
    /// JSON Schema describing the expected message `data` for this action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message_schema: Option<serde_json::Value>,
    /// JSON Schema describing the response `data` for this action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_schema: Option<serde_json::Value>,
}

/// A database collection (table) declared by a block.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CollectionSchema {
    pub name: String,
    pub fields: Vec<FieldSchema>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub indexes: Vec<IndexSchema>,
}

/// A field (column) in a collection.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FieldSchema {
    pub name: String,
    pub field_type: String,
    #[serde(default)]
    pub unique: bool,
    #[serde(default)]
    pub optional: bool,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub default_value: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub reference: String,
}

/// An index on a collection.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct IndexSchema {
    pub fields: Vec<String>,
    #[serde(default)]
    pub unique: bool,
}

// ---------------------------------------------------------------------------
// Schema builder helpers
// ---------------------------------------------------------------------------

impl CollectionSchema {
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            fields: Vec::new(),
            indexes: Vec::new(),
        }
    }

    pub fn field(mut self, name: &str, field_type: &str) -> Self {
        self.fields.push(FieldSchema::new(name, field_type));
        self
    }

    pub fn field_unique(mut self, name: &str, field_type: &str) -> Self {
        self.fields
            .push(FieldSchema::new(name, field_type).set_unique());
        self
    }

    pub fn field_optional(mut self, name: &str, field_type: &str) -> Self {
        self.fields
            .push(FieldSchema::new(name, field_type).set_optional());
        self
    }

    pub fn field_default(mut self, name: &str, field_type: &str, default: &str) -> Self {
        self.fields
            .push(FieldSchema::new(name, field_type).set_default(default));
        self
    }

    pub fn field_ref(mut self, name: &str, field_type: &str, reference: &str) -> Self {
        self.fields
            .push(FieldSchema::new(name, field_type).set_ref(reference));
        self
    }

    pub fn index(mut self, fields: &[&str]) -> Self {
        self.indexes.push(IndexSchema {
            fields: fields.iter().map(|s| s.to_string()).collect(),
            unique: false,
        });
        self
    }

    pub fn unique_index(mut self, fields: &[&str]) -> Self {
        self.indexes.push(IndexSchema {
            fields: fields.iter().map(|s| s.to_string()).collect(),
            unique: true,
        });
        self
    }
}

impl FieldSchema {
    pub fn new(name: &str, field_type: &str) -> Self {
        Self {
            name: name.to_string(),
            field_type: field_type.to_string(),
            unique: false,
            optional: false,
            default_value: String::new(),
            reference: String::new(),
        }
    }

    pub fn set_unique(mut self) -> Self {
        self.unique = true;
        self
    }
    pub fn set_optional(mut self) -> Self {
        self.optional = true;
        self
    }
    pub fn set_default(mut self, val: &str) -> Self {
        self.default_value = val.to_string();
        self
    }
    pub fn set_ref(mut self, reference: &str) -> Self {
        self.reference = reference.to_string();
        self
    }
}

/// A UI route declared by a block for SSR page serving.
///
/// Blocks declare their page routes via `Block::ui_routes()`. The router
/// automatically prefixes each path with `/b/{block_short_name}`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UiRoute {
    /// Relative path (e.g., "/login", "/dashboard", "/").
    pub path: String,
    /// Required roles to access this route.
    /// Empty = public, `["*"]` = any authenticated user, `["admin"]` = admin only.
    pub roles: Vec<String>,
}

impl UiRoute {
    pub fn new(path: &str, roles: &[&str]) -> Self {
        Self {
            path: path.to_string(),
            roles: roles.iter().map(|r| r.to_string()).collect(),
        }
    }

    /// Public route — no authentication required.
    pub fn public(path: &str) -> Self {
        Self::new(path, &[])
    }

    /// Authenticated route — any logged-in user.
    pub fn authenticated(path: &str) -> Self {
        Self::new(path, &["*"])
    }

    /// Admin-only route.
    pub fn admin(path: &str) -> Self {
        Self::new(path, &["admin"])
    }
}

/// HTTP-level request action mapped from method to WAFER semantics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RequestAction {
    Retrieve,
    Create,
    Update,
    Delete,
    Execute,
}

impl RequestAction {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Retrieve => "retrieve",
            Self::Create => "create",
            Self::Update => "update",
            Self::Delete => "delete",
            Self::Execute => "execute",
        }
    }
}

// ---------------------------------------------------------------------------
// ErrorCode backward-compatible constants
// ---------------------------------------------------------------------------

impl crate::ErrorCode {
    pub const OK: Self = Self::Ok;
    pub const CANCELLED: Self = Self::Cancelled;
    pub const UNKNOWN: Self = Self::Unknown;
    pub const INVALID_ARGUMENT: Self = Self::InvalidArgument;
    pub const DEADLINE_EXCEEDED: Self = Self::DeadlineExceeded;
    pub const NOT_FOUND: Self = Self::NotFound;
    pub const ALREADY_EXISTS: Self = Self::AlreadyExists;
    pub const PERMISSION_DENIED: Self = Self::PermissionDenied;
    pub const RESOURCE_EXHAUSTED: Self = Self::ResourceExhausted;
    pub const FAILED_PRECONDITION: Self = Self::FailedPrecondition;
    pub const ABORTED: Self = Self::Aborted;
    pub const OUT_OF_RANGE: Self = Self::OutOfRange;
    pub const UNIMPLEMENTED: Self = Self::Unimplemented;
    pub const INTERNAL: Self = Self::Internal;
    pub const UNAVAILABLE: Self = Self::Unavailable;
    pub const DATA_LOSS: Self = Self::DataLoss;
    pub const UNAUTHENTICATED: Self = Self::Unauthenticated;
}

impl From<&str> for crate::ErrorCode {
    fn from(s: &str) -> Self {
        match s {
            "ok" => Self::Ok,
            "cancelled" => Self::Cancelled,
            "unknown" => Self::Unknown,
            "invalid_argument" | "invalid-argument" | "bad_request" => Self::InvalidArgument,
            "deadline_exceeded" | "deadline-exceeded" => Self::DeadlineExceeded,
            "not_found" | "not-found" => Self::NotFound,
            "already_exists" | "already-exists" => Self::AlreadyExists,
            "permission_denied" | "permission-denied" => Self::PermissionDenied,
            "resource_exhausted" | "resource-exhausted" => Self::ResourceExhausted,
            "failed_precondition" | "failed-precondition" => Self::FailedPrecondition,
            "aborted" => Self::Aborted,
            "out_of_range" | "out-of-range" => Self::OutOfRange,
            "unimplemented" | "not_implemented" => Self::Unimplemented,
            "internal" => Self::Internal,
            "unavailable" => Self::Unavailable,
            "data_loss" | "data-loss" => Self::DataLoss,
            "unauthenticated" => Self::Unauthenticated,
            _ => Self::Unknown,
        }
    }
}

// ---------------------------------------------------------------------------
// WaferError helpers
// ---------------------------------------------------------------------------

impl crate::WaferError {
    /// Create a new error with the given code and message (empty meta).
    pub fn new(code: impl Into<crate::ErrorCode>, message: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            meta: Vec::new(),
        }
    }
}

// ---------------------------------------------------------------------------
// Message helpers
// ---------------------------------------------------------------------------

impl crate::Message {
    /// Create a new message with the given kind and data (empty meta).
    pub fn new(kind: impl Into<String>, data: impl AsRef<[u8]>) -> Self {
        Self {
            kind: kind.into(),
            data: data.as_ref().to_vec(),
            meta: Vec::new(),
        }
    }

    /// Get a meta value by key, returning `""` if not found.
    pub fn get_meta(&self, key: &str) -> &str {
        self.meta
            .iter()
            .find(|entry| entry.key == key)
            .map(|entry| entry.value.as_str())
            .unwrap_or("")
    }

    /// Set a meta value, updating an existing entry or appending a new one.
    pub fn set_meta(&mut self, key: impl Into<String>, value: impl Into<String>) {
        let key = key.into();
        let value = value.into();
        if let Some(entry) = self.meta.iter_mut().find(|e| e.key == key) {
            entry.value = value;
        } else {
            self.meta.push(crate::MetaEntry { key, value });
        }
    }

    /// Return a Drop result (like `drop_msg` but takes `&self` instead of consuming).
    pub fn drop_msg_ref(&self) -> crate::BlockResult {
        crate::BlockResult {
            action: crate::Action::Drop,
            response: None,
            error: None,
            message: Some(self.clone()),
        }
    }

    /// Return a Continue result carrying a clone of this message.
    pub fn cont_ref(&self) -> crate::BlockResult {
        crate::BlockResult {
            action: crate::Action::Continue,
            response: None,
            error: None,
            message: Some(self.clone()),
        }
    }

    /// Deserialize `data` as JSON into `T`.
    pub fn decode<T: serde::de::DeserializeOwned>(&self) -> Result<T, String> {
        serde_json::from_slice(&self.data).map_err(|e| e.to_string())
    }

    /// Shortcut for `get_meta(META_REQ_ACTION)`.
    pub fn action(&self) -> &str {
        self.get_meta(crate::meta::META_REQ_ACTION)
    }

    /// Shortcut for `get_meta(META_REQ_RESOURCE)`.
    pub fn path(&self) -> &str {
        self.get_meta(crate::meta::META_REQ_RESOURCE)
    }

    /// Shortcut for the authenticated user ID.
    pub fn user_id(&self) -> &str {
        self.get_meta(crate::meta::META_AUTH_USER_ID)
    }

    /// Shortcut for `get_meta("req.client.ip")`.
    pub fn remote_addr(&self) -> &str {
        self.get_meta(crate::meta::META_REQ_CLIENT_IP)
    }

    /// Get a cookie value by name from the Cookie header.
    pub fn cookie(&self, name: &str) -> &str {
        let cookies = self.header("cookie");
        if cookies.is_empty() {
            return "";
        }
        for part in cookies.split(';') {
            let part = part.trim();
            if let Some(eq) = part.find('=') {
                if &part[..eq] == name {
                    return &part[eq + 1..];
                }
            }
        }
        ""
    }

    /// Get an HTTP header value (case-insensitive).
    pub fn header(&self, name: &str) -> &str {
        let key = format!("http.header.{}", name);
        let val = self.get_meta(&key);
        if !val.is_empty() {
            return val;
        }
        let key_lower = format!("http.header.{}", name.to_lowercase());
        self.get_meta(&key_lower)
    }

    /// Get a URL path variable by name (from `req.param.{name}`).
    pub fn var(&self, name: &str) -> &str {
        let key = format!("{}{}", crate::meta::META_REQ_PARAM_PREFIX, name);
        self.get_meta(&key)
    }

    /// Get a query parameter by name (from `req.query.{name}`).
    pub fn query(&self, name: &str) -> &str {
        let key = format!("{}{}", crate::meta::META_REQ_QUERY_PREFIX, name);
        self.get_meta(&key)
    }

    /// Get the raw body bytes.
    pub fn body(&self) -> &[u8] {
        &self.data
    }

    /// Set data from a serializable value.
    pub fn set_data<T: serde::Serialize>(&mut self, data: &T) -> Result<(), String> {
        self.data = serde_json::to_vec(data).map_err(|e| e.to_string())?;
        Ok(())
    }

    /// Collect all query parameters into a HashMap.
    pub fn query_params(&self) -> HashMap<String, String> {
        let prefix = crate::meta::META_REQ_QUERY_PREFIX;
        self.meta
            .iter()
            .filter(|e| e.key.starts_with(prefix))
            .map(|e| (e.key[prefix.len()..].to_string(), e.value.clone()))
            .collect()
    }

    /// Parse pagination query parameters (page, page_size, offset).
    pub fn pagination_params(&self, default_page_size: usize) -> (usize, usize, usize) {
        let page: usize = self.query("page").parse().unwrap_or(1).max(1);
        let page_size: usize = self
            .query("page_size")
            .parse()
            .unwrap_or(default_page_size)
            .min(100);
        let offset = (page - 1) * page_size;
        (page, page_size, offset)
    }
}

// ---------------------------------------------------------------------------
// BlockResult helpers
// ---------------------------------------------------------------------------

impl crate::BlockResult {
    /// Create an error result with no message.
    pub fn error(err: crate::WaferError) -> Self {
        Self {
            action: crate::Action::Error,
            response: None,
            error: Some(err),
            message: None,
        }
    }
}

// ---------------------------------------------------------------------------
// MetaAccess trait for Vec<MetaEntry>
// ---------------------------------------------------------------------------

/// Convenience trait giving `HashMap`-like access to `Vec<MetaEntry>`.
pub trait MetaAccess {
    fn get(&self, key: &str) -> Option<&str>;
    fn set(&mut self, key: String, value: String);
    fn contains_key(&self, key: &str) -> bool;
}

impl MetaAccess for Vec<crate::MetaEntry> {
    fn get(&self, key: &str) -> Option<&str> {
        self.iter().find(|e| e.key == key).map(|e| e.value.as_str())
    }

    fn set(&mut self, key: String, value: String) {
        if let Some(entry) = self.iter_mut().find(|e| e.key == key) {
            entry.value = value;
        } else {
            self.push(crate::MetaEntry { key, value });
        }
    }

    fn contains_key(&self, key: &str) -> bool {
        self.iter().any(|e| e.key == key)
    }
}

impl MetaAccess for [crate::MetaEntry] {
    fn get(&self, key: &str) -> Option<&str> {
        self.iter().find(|e| e.key == key).map(|e| e.value.as_str())
    }

    fn set(&mut self, _key: String, _value: String) {
        panic!("cannot insert into a slice; use Vec<MetaEntry> instead");
    }

    fn contains_key(&self, key: &str) -> bool {
        self.iter().any(|e| e.key == key)
    }
}

/// Convert a `HashMap<String, String>` into `Vec<MetaEntry>`.
pub fn hashmap_to_meta(map: HashMap<String, String>) -> Vec<crate::MetaEntry> {
    map.into_iter()
        .map(|(k, v)| crate::MetaEntry { key: k, value: v })
        .collect()
}

/// Convert `Vec<MetaEntry>` into `HashMap<String, String>`.
pub fn meta_to_hashmap(meta: &[crate::MetaEntry]) -> HashMap<String, String> {
    meta.iter()
        .map(|e| (e.key.clone(), e.value.clone()))
        .collect()
}

// ---------------------------------------------------------------------------
// InstanceMode helpers
// ---------------------------------------------------------------------------

impl std::fmt::Display for crate::InstanceMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            crate::InstanceMode::PerNode => write!(f, "per-node"),
            crate::InstanceMode::Singleton => write!(f, "singleton"),
            crate::InstanceMode::PerFlow => write!(f, "per-flow"),
            crate::InstanceMode::PerExecution => write!(f, "per-execution"),
        }
    }
}

impl crate::InstanceMode {
    /// Parse an instance mode from a string (e.g. from flow config).
    pub fn parse(s: &str) -> Self {
        match s {
            "singleton" => Self::Singleton,
            "per-flow" => Self::PerFlow,
            "per-execution" => Self::PerExecution,
            _ => Self::PerNode,
        }
    }
}

// ---------------------------------------------------------------------------
// BlockResult helpers (continued)
// ---------------------------------------------------------------------------

impl crate::BlockResult {
    /// Create a continue result carrying the given message.
    pub fn continue_with(msg: crate::Message) -> Self {
        Self {
            action: crate::Action::Continue,
            response: None,
            error: None,
            message: Some(msg),
        }
    }
}
