// Auto-generated by wafer-common/codegen — DO NOT EDIT.

package wafer

// gRPC-style error codes for WAFER.
const (
	// Success
	ErrorCodeOk = "ok"
	// Operation was cancelled
	ErrorCodeCancelled = "cancelled"
	// Unknown error
	ErrorCodeUnknown = "unknown"
	// Invalid argument provided
	ErrorCodeInvalidArgument = "invalid_argument"
	// Deadline expired before operation completed
	ErrorCodeDeadlineExceeded = "deadline_exceeded"
	// Requested entity not found
	ErrorCodeNotFound = "not_found"
	// Entity already exists
	ErrorCodeAlreadyExists = "already_exists"
	// Permission denied
	ErrorCodePermissionDenied = "permission_denied"
	// Resource exhausted
	ErrorCodeResourceExhausted = "resource_exhausted"
	// Operation rejected due to failed precondition
	ErrorCodeFailedPrecondition = "failed_precondition"
	// Operation aborted
	ErrorCodeAborted = "aborted"
	// Value out of valid range
	ErrorCodeOutOfRange = "out_of_range"
	// Operation not implemented
	ErrorCodeUnimplemented = "unimplemented"
	// Internal error
	ErrorCodeInternal = "internal"
	// Service unavailable
	ErrorCodeUnavailable = "unavailable"
	// Unrecoverable data loss
	ErrorCodeDataLoss = "data_loss"
	// Request not authenticated
	ErrorCodeUnauthenticated = "unauthenticated"
)
