[workspace]

[package]
name = "dispatch-guest"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
wafer-sdk = { path = "../../../../sdks/rust" }
serde_json = "1"

[profile.release]
opt-level = 3
lto = false
codegen-units = 1
panic = "abort"
