"""Go code generation templates for WAFER common definitions."""


def _to_pascal(snake: str) -> str:
    """Convert snake_case to PascalCase (no prefix)."""
    return "".join(p.capitalize() for p in snake.split("_"))


def _go_const_name(prefix: str, name: str) -> str:
    """Convert a snake_case name to Go PascalCase with prefix."""
    return f"{prefix}{_to_pascal(name)}"


def generate_error_codes(codes: dict) -> str:
    """Generate Go error code constants.

    Wire values are PascalCase to match the Rust ErrorCode enum's Serde
    default (no `rename_all` attribute → variant name verbatim). The
    canonical Rust enum lives at crates/wafer-block/src/core_types.rs.
    """
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "package common",
        "",
        "// gRPC-style error codes for WAFER. Wire values are PascalCase to",
        "// match the Rust ErrorCode enum's Serde default.",
        "const (",
    ]
    for name, info in codes.items():
        const_name = _go_const_name("ErrorCode", name)
        desc = info["description"]
        lines.append(f'\t// {desc}')
        lines.append(f'\t{const_name} = "{_to_pascal(name)}"')
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def generate_meta_keys(meta: dict) -> str:
    """Generate Go meta key constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "package common",
        "",
        "// Canonical metadata key constants for WAFER.",
        "const (",
    ]

    for section, entries in meta.items():
        if section.endswith(".prefixes"):
            continue
        prefix_parts = section.split(".")
        go_prefix = "".join(p.capitalize() for p in prefix_parts)
        for key, value in entries.items():
            if isinstance(value, str):
                parts = key.split("_")
                go_name = "".join(p.capitalize() for p in parts)
                const_name = f"MetaKey{go_prefix}{go_name}"
                lines.append(f'\t{const_name} = "{value}"')

    for section, entries in meta.items():
        if not section.endswith(".prefixes"):
            continue
        base = section.replace(".prefixes", "")
        prefix_parts = base.split(".")
        go_prefix = "".join(p.capitalize() for p in prefix_parts)
        for key, value in entries.items():
            parts = key.split("_")
            go_name = "".join(p.capitalize() for p in parts)
            const_name = f"MetaKey{go_prefix}{go_name}Prefix"
            lines.append(f'\t{const_name} = "{value}"')

    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def generate_service_names(data: dict) -> str:
    """Generate Go service name constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "package common",
        "",
        "// Service name and operation constants for WAFER.",
        "const (",
    ]
    for name, value in data.get("services", {}).items():
        const_name = _go_const_name("ServiceName", name)
        lines.append(f'\t{const_name} = "{value}"')

    for svc, ops in data.get("operations", {}).items():
        for op_name, op_value in ops.items():
            parts = svc.split("_") + op_name.split("_")
            go_name = "".join(p.capitalize() for p in parts)
            const_name = f"ServiceOp{go_name}"
            lines.append(f'\t{const_name} = "{op_value}"')
    lines.append(")")
    lines.append("")
    return "\n".join(lines)
