"""Rust code generation templates for WAFER common definitions."""


def generate_error_codes(codes: dict) -> str:
    """Generate Rust error code constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/// gRPC-style error codes for WAFER.",
        "pub struct ErrorCode;",
        "",
        "impl ErrorCode {",
    ]
    for name, info in codes.items():
        desc = info["description"]
        const_name = name.upper()
        lines.append(f'    /// {desc}')
        lines.append(f'    pub const {const_name}: &str = "{name}";')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_meta_keys(meta: dict) -> str:
    """Generate Rust meta key constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/// Canonical metadata key constants for WAFER.",
        "pub struct MetaKey;",
        "",
        "impl MetaKey {",
    ]

    for section, entries in meta.items():
        if section.endswith(".prefixes"):
            continue
        prefix = section.upper()
        for key, value in entries.items():
            if isinstance(value, str):
                const_name = f"{prefix}_{key.upper()}"
                lines.append(f'    pub const {const_name}: &str = "{value}";')

    # Handle prefixes
    for section, entries in meta.items():
        if not section.endswith(".prefixes"):
            continue
        base = section.replace(".prefixes", "").upper()
        for key, value in entries.items():
            const_name = f"{base}_{key.upper()}_PREFIX"
            lines.append(f'    pub const {const_name}: &str = "{value}";')

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_service_names(data: dict) -> str:
    """Generate Rust service name constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/// Service name constants for WAFER.",
        "pub struct ServiceName;",
        "",
        "impl ServiceName {",
    ]
    for name, value in data.get("services", {}).items():
        const_name = name.upper()
        lines.append(f'    pub const {const_name}: &str = "{value}";')
    lines.append("}")
    lines.append("")

    lines.append("/// Service operation constants for WAFER.")
    lines.append("pub struct ServiceOp;")
    lines.append("")
    lines.append("impl ServiceOp {")
    for svc, ops in data.get("operations", {}).items():
        for op_name, op_value in ops.items():
            const_name = f"{svc.upper()}_{op_name.upper()}"
            lines.append(f'    pub const {const_name}: &str = "{op_value}";')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_constants(has_error_codes: bool, has_meta_keys: bool, has_service_names: bool) -> str:
    """Generate Rust constants.rs that re-exports all modules."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
    ]
    if has_error_codes:
        lines.append("mod error_codes;")
        lines.append("pub use error_codes::ErrorCode;")
    if has_meta_keys:
        lines.append("mod meta_keys;")
        lines.append("pub use meta_keys::MetaKey;")
    if has_service_names:
        lines.append("mod service_names;")
        lines.append("pub use service_names::{ServiceName, ServiceOp};")
    lines.append("")
    return "\n".join(lines)
