"""TypeScript code generation templates for WAFER common definitions."""


def generate_error_codes(codes: dict) -> str:
    """Generate TypeScript error code constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/** gRPC-style error codes for WAFER. */",
        "export const ErrorCode = {",
    ]
    for name, info in codes.items():
        const_name = name.upper()
        desc = info["description"]
        lines.append(f"  /** {desc} */")
        lines.append(f"  {const_name}: '{name}',")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];")
    lines.append("")
    return "\n".join(lines)


def _meta_section_prefix(section: str, entries: dict) -> str:
    """Derive the const-name prefix for a section.

    If every value in the section shares the same dot-prefix (e.g. `req.`,
    `resp.`), use that prefix uppercased — so `req.action` becomes
    `META_REQ_ACTION`, matching the canonical wire format. Otherwise fall
    back to the section name (e.g. `database` → `DATABASE`).
    """
    base_section = section.replace(".prefixes", "")
    first_segments = set()
    for value in entries.values():
        if isinstance(value, str) and "." in value:
            first_segments.add(value.split(".", 1)[0])
    if len(first_segments) == 1:
        return next(iter(first_segments)).upper()
    return base_section.upper().replace(".", "_")


def generate_meta_keys(meta: dict) -> str:
    """Generate TypeScript meta key constants.

    Emits one named `META_<SECTION>_<KEY>` export per entry, matching the
    convention used by the Rust hand-rolled `wafer-block::meta` module and
    the `wafer-client-js` SDK's public API.
    """
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "// Canonical metadata key constants for WAFER. Names mirror the",
        "// Rust `wafer-block::meta` constants so SDKs can re-export directly.",
        "",
    ]

    for section, entries in meta.items():
        if section.endswith(".prefixes"):
            continue
        prefix = _meta_section_prefix(section, entries)
        for key, value in entries.items():
            if isinstance(value, str):
                const_name = f"META_{prefix}_{key.upper()}"
                lines.append(f"export const {const_name} = '{value}';")

    for section, entries in meta.items():
        if not section.endswith(".prefixes"):
            continue
        prefix = _meta_section_prefix(section, entries)
        for key, value in entries.items():
            const_name = f"META_{prefix}_{key.upper()}_PREFIX"
            lines.append(f"export const {const_name} = '{value}';")

    lines.append("")
    return "\n".join(lines)


def generate_service_names(data: dict) -> str:
    """Generate TypeScript service name constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/** Service name constants for WAFER. */",
        "export const ServiceName = {",
    ]
    for name, value in data.get("services", {}).items():
        const_name = name.upper()
        lines.append(f"  {const_name}: '{value}',")
    lines.append("} as const;")
    lines.append("")

    lines.append("/** Service operation constants for WAFER. */")
    lines.append("export const ServiceOp = {")
    for svc, ops in data.get("operations", {}).items():
        for op_name, op_value in ops.items():
            const_name = f"{svc.upper()}_{op_name.upper()}"
            lines.append(f"  {const_name}: '{op_value}',")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)
