"""TypeScript code generation templates for WAFER common definitions."""


def generate_error_codes(codes: dict) -> str:
    """Generate TypeScript error code constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/** gRPC-style error codes for WAFER. */",
        "export const ErrorCode = {",
    ]
    for name, info in codes.items():
        const_name = name.upper()
        desc = info["description"]
        lines.append(f"  /** {desc} */")
        lines.append(f"  {const_name}: '{name}',")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];")
    lines.append("")
    return "\n".join(lines)


def generate_meta_keys(meta: dict) -> str:
    """Generate TypeScript meta key constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/** Canonical metadata key constants for WAFER. */",
        "export const MetaKey = {",
    ]

    for section, entries in meta.items():
        if section.endswith(".prefixes"):
            continue
        prefix = section.upper().replace(".", "_")
        for key, value in entries.items():
            if isinstance(value, str):
                const_name = f"{prefix}_{key.upper()}"
                lines.append(f"  {const_name}: '{value}',")

    for section, entries in meta.items():
        if not section.endswith(".prefixes"):
            continue
        base = section.replace(".prefixes", "").upper().replace(".", "_")
        for key, value in entries.items():
            const_name = f"{base}_{key.upper()}_PREFIX"
            lines.append(f"  {const_name}: '{value}',")

    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def generate_service_names(data: dict) -> str:
    """Generate TypeScript service name constants."""
    lines = [
        "// Auto-generated by wafer-common/codegen — DO NOT EDIT.",
        "",
        "/** Service name constants for WAFER. */",
        "export const ServiceName = {",
    ]
    for name, value in data.get("services", {}).items():
        const_name = name.upper()
        lines.append(f"  {const_name}: '{value}',")
    lines.append("} as const;")
    lines.append("")

    lines.append("/** Service operation constants for WAFER. */")
    lines.append("export const ServiceOp = {")
    for svc, ops in data.get("operations", {}).items():
        for op_name, op_value in ops.items():
            const_name = f"{svc.upper()}_{op_name.upper()}"
            lines.append(f"  {const_name}: '{op_value}',")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)
