[package]
name = "wafer-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for creating, building, testing, and packaging WAFER blocks"

[[bin]]
name = "wafer"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = { workspace = true }
clap = { version = "4", features = ["derive"] }
dirs = "5"
hex = "0.4"
reqwest = { workspace = true, features = ["multipart"] }
rpassword = "7"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
terminal_size = "0.3"
toml = { workspace = true }
tokio = { workspace = true, features = ["full"] }
wafer-block = { workspace = true }
wasmi = { workspace = true }
webbrowser = "1"

[dev-dependencies]
tempfile = { workspace = true }
wiremock = "0.6"
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
